services:
  zenoh:
    init: true
    image: eclipse/zenoh:1.0.1
    ports:
      - 7447:7447
      - 8000:8000
    volumes:
      - ./.zenoh:/root/.zenoh
    command: -c /root/.zenoh/meshnetworkx.json5

  zenoh-host:
    # usefull to run in host mode when running meshnetworkx outside docker.
    profiles:
        - donotstart
    init: true
    image: eclipse/zenoh:1.0.1
    ports:
      - 7447:7447
      - 8000:8000
    volumes:
      - ./.zenoh:/root/.zenoh
    command: -c /root/.zenoh/meshnetworkx.json5
    network_mode: host

  meshnetworkx:  # the experimental script.
    init: true
    build: .
    command: ["uv", "run", "examples/two_device/main.py"]
    volumes:
      - ./examples:/workdir/examples/
      - ./src:/workdir/src/
    depends_on:
        - zenoh
    environment:
      # ZENOH_ENDPOINTS: tcp/localhost:7447
      MACHINE: 1
      PYTHONUNBUFFERED: 1
    ports:
      - 8080:8080
