services:
  zenoh:
    init: true
    image: eclipse/zenoh
    ports:
      - 7447:7447
      - 8000:8000
    volumes:
      - ./.zenoh:/root/.zenoh
    command: -c /root/.zenoh/meshnetworkx.json5

  zenoh-host:
    # usefull to run in host mode when running meshnetworkx outside docker.
    profiles:
        - donotstart
    init: true
    image: eclipse/zenoh
    ports:
      - 7447:7447
      - 8000:8000
    volumes:
      - ./.zenoh:/root/.zenoh
    command: -c /root/.zenoh/meshnetworkx.json5
    network_mode: host

  meshnetworkx:  # the experimental script.
    init: true
    build: .
    command: ["uv", "run", "examples/main.py"]
    depends_on:
        - zenoh
